version: 1
disable_existing_loggers: no
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(asctime)s - %(name)s - %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
handlers:
  sen0386_hw_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/sen0386_hw.log
    maxBytes: 10485760 
    backupCount: 20
    encoding: utf8
  lm298_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/lm298.log
    maxBytes: 10485760 
    backupCount: 20
    encoding: utf8
  main_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/main.log
    maxBytes: 10485760 
    backupCount: 20
    encoding: utf8
root:
  level: DEBUG
  handlers: []
  propagate: yes
loggers:
  main:
    level: INFO
    handlers: [main_file_handler]
    propagate: no
  sen0386:
    level: INFO
    handlers: [main_file_handler]
    propagate: no
  sen0386_hw:
    level: INFO
    handlers: [sen0386_hw_file_handler]
    propagate: no
  lm298:
    level: INFO
    handlers: [main_file_handler]
    propagate: no

